### ISSUE TITLE
ParseFloatError on startup

### ISSUE THREAD

**Issue by gmorenz** [mmstick/systemd-manager#6]
This is on Arch Linux, with a pretty normal setup.

```
[normal@malware systemd-manager]$ RUST_BACKTRACE=1 cargo run
     Running `target/debug/systemd-manager`
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseFloatError { kind: Invalid }', ../src/libcore/result.rs:785
stack backtrace:
   1:     0x563829b27740 - std::sys::backtrace::tracing::imp::write::h9fb600083204ae7f
   2:     0x563829b2b6db - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::hca543c34f11229ac
   3:     0x563829b2b363 - std::panicking::default_hook::hc2c969e7453d080c
   4:     0x563829b1e0ff - std::sys_common::unwind::begin_unwind_inner::h30e12d15ce2b2e25
   5:     0x563829b1ec08 - std::sys_common::unwind::begin_unwind_fmt::hb2de8a9968d38523
   6:     0x563829b26b01 - rust_begin_unwind
   7:     0x563829b6191f - core::panicking::panic_fmt::h257ceb0aa351d801
   8:     0x563829ac4811 - core::result::unwrap_failed::h9a4f9b64476df8f7
                        at ../src/libcore/macros.rs:29
   9:     0x563829ac46c0 - _<std..result..Result<T, E>>::unwrap::h25badbe3cadff716
                        at ../src/libcore/result.rs:723
  10:     0x563829ac3da9 - systemd_manager::systemd_analyze::blame::parse_time::haaf3c3e3c90cd5be
                        at src/systemd_analyze.rs:15
  11:     0x563829abdcb2 - systemd_manager::systemd_analyze::blame::_$u7b$$u7b$closure$u7d$$u7d$::hafa9fe49e98a7bb9
                        at src/systemd_analyze.rs:24
  12:     0x563829abdb9b - core::ops::impls::_<impl std..ops..FnOnce<A> for &'a mut F>::call_once::h2356c29ef45f6a76
                        at ../src/libcore/ops.rs:1998
  13:     0x563829abdb1f - _<std..option..Option<T>>::map::h9d8f5039951f275c
                        at ../src/libcore/option.rs:385
  14:     0x563829abdaae - _<std..iter..Map<I, F> as std..iter..Iterator>::next::h6fa5be0e923cd3f4
                        at ../src/libcore/iter/mod.rs:761
  15:     0x563829ac02d2 - _<std..vec..Vec<T>>::extend_desugared::h4e090c0a240bba6d
                        at ../src/libcollections/vec.rs:1417
  16:     0x563829abd8c9 - _<std..vec..Vec<T> as std..iter..FromIterator<T>>::from_iter::hdba262cb1a9e1bb7
                        at ../src/libcollections/vec.rs:1325
  17:     0x563829abd417 - core::iter::iterator::Iterator::collect::hb180804f43673400
                        at ../src/libcore/iter/iterator.rs:1208
  18:     0x563829abd332 - systemd_manager::systemd_analyze::blame::heaaa57490d2b1465
                        at src/systemd_analyze.rs:20
  19:     0x563829adf577 - systemd_manager::systemd_gui::setup_systemd_analyze::hc664aa7befb6fb15
                        at src/systemd_gui.rs:63
  20:     0x563829abacf9 - systemd_manager::systemd_gui::launch::hec754e8cc76f2b1b
                        at src/systemd_gui.rs:144
  21:     0x563829aba1b8 - systemd_manager::main::h22a01905651f008f
                        at src/main.rs:8
  22:     0x563829b2afa4 - std::sys_common::unwind::try::try_fn::h04c0c89e4add6cc4
  23:     0x563829b26a8b - __rust_try
  24:     0x563829b2a9eb - std::rt::lang_start::h61f4934e780b4dfc
  25:     0x563829abd0b9 - main
  26:     0x7fc5adbe3740 - __libc_start_main
  27:     0x563829aba0a8 - _start
  28:                0x0 - <unknown>
error: Process didn't exit successfully: `target/debug/systemd-manager` (exit code: 101)
```

**Comment by gmorenz** [comment]
Problem occurs on a `input` of `2min`

**Comment by mmstick** [comment]
I see. Well that's an easy fix. I didn't anticipate usage of a `min` suffix as nothing on my system takes nearly that long (3s boot times). I shouldn't be causing a panic though just because of a float error though, so I'll fix that shortly. I will update you when I have it fixed.

**Comment by mmstick** [comment]
The code has been refactored and a fix has been applied. It should now account for instances of `min` as a suffix and if a float error occurs, the value returned will be `0` rather than panicking. Tell me if it works for you and I will close the issue.

**Comment by gmorenz** [comment]
The immediate problem is solved, but I can now see that the 2min time was probably a result of another bug... which makes sense since it boots in well under a minute.

I'm not sure how you want to manage issues, should this problem go in a new one?

![screenshot from 2016-05-17 10-15-56](https://cloud.githubusercontent.com/assets/595972/15325424/5d2f3b30-1c18-11e6-8b0a-948352f37ea6.png)

**Comment by gmorenz** [comment]
Looks like it's just another parsing issue with minutes:

```
[normal@malware systemd-manager]$ systemd-analyze blame
    3min 38.514s updatedb.service
         15.443s openntpd.service
         15.245s man-db.service
          9.334s dev-sda8.device
          2.248s NetworkManager.service
          2.038s accounts-daemon.service
          1.780s systemd-udevd.service
          1.497s systemd-journal-flush.service
          1.405s colord.service
          1.313s systemd-journald.service
          1.171s gdm.service
           989ms systemd-sysctl.service
           937ms logrotate.service
           841ms polkit.service
           811ms systemd-random-seed.service
           697ms systemd-tmpfiles-setup-dev.service
           585ms shadow.service
           558ms user@120.service
           544ms systemd-logind.service
           478ms user@1000.service
           371ms upower.service
           361ms dev-hugepages.mount
           279ms systemd-tmpfiles-clean.service
           265ms systemd-modules-load.service
           264ms systemd-backlight@backlight:intel_backlight.service
           261ms lm_sensors.service
           260ms systemd-user-sessions.service
           243ms udisks2.service
           212ms wpa_supplicant.service
           200ms tmp.mount
           176ms systemd-remount-fs.service
           176ms systemd-rfkill.service
           155ms systemd-vconsole-setup.service
           132ms systemd-tmpfiles-setup.service
            90ms dev-mqueue.mount
            82ms systemd-udev-trigger.service
            61ms sys-kernel-debug.mount
            59ms systemd-update-utmp.service
            32ms kmod-static-nodes.service
            15ms rtkit-daemon.service
            10ms sys-kernel-config.mount
             2ms sys-fs-fuse-connections.mount
```

**Comment by mmstick** [comment]
I will have a fix pushed shortly.

**Comment by mmstick** [comment]
I have pushed a fix and used your information as input for unit tests in the `analyze.rs` source code file, therefore you should have accurate values now. If it's fixed for you, you can close the issue.

I think it's odd that the systemd maintainers decided to use decimals for seconds if they are already going to split time into multiple units once the unit gets to minutes. If it were my choice, I'd make it consistent and also write it out as "9s 334ms" rather than "9.334s".

In any case, the new patch will be able to handle the current setup and if they ever implement "3min 9s 334ms" then that will work too. The fix is to collect each of the whitespace-delimited values into a single `Vec`, `pop()` the last value as the service, and then `fold()` across the original `Vec` to collect the time.

**Comment by gmorenz** [comment]
Works now :+1:
